#!/bin/sh

# FHE 05 Sep 2018 adapted from study/arabic/

FN=$1
if [[ $(basename $FN) == README.md ]]; then
    OUT=$(dirname $FN)/index.html
else
    OUT=${FN%.md}.html
fi

>&2 echo Writing to $OUT

set -x
    # get rid of <p> around main <div>
    # remove closing tags
multimarkdown $FN -o - | \
    perl -pe '/<div id="page-wrap">/ && s/<\/?p>//g' | \
    grep -v 'my-source-command' | \
    head -n -3 \
    > $OUT

# cat >> $OUT <<EOF
# <p><em>Last updated $(date +'%-d %B %y')</em></p>
# </div>
# </body>
# </html>
# EOF

cat >> $OUT <<EOF
</div>
</body>
</html>
EOF
