#!/bin/sh

# FHE 05 Sep 2018 adapted from study/arabic/

FN=$1
if [[ $(basename $FN) == README.md ]]; then
    OUT=$(dirname $FN)/index.html
else
    OUT=${FN%.md}.html
fi

>&2 echo Writing to $OUT

multimarkdown $FN -o - | \
    # get rid of <p> around main <div>
    perl -pe '/<div id="page-wrap">/ && s/<\/?p>//g' | \
    grep -v 'my-source-command' | \
    # remove closing tags
    head -n -3 \
    > $OUT

cat >> $OUT <<EOF
</div>
</body>
</html>
EOF
